server:
  port: 31001
spring:
  application:
    name: xc-service-manager-cms
  data:
    mongodb:
      uri: mongodb://101.200.133.224:27017
      database: cms
      username: ruipeng
      password: 123456
